### ISSUE TITLE
Schematron resources missing in Win builds

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/jprofile#2]
```
Traceback (most recent call last):
```

Running executable built with PyInstaller produces this error:

```
  File "<string>", line 49, in <module>
  File "c:\pyinstall\PyInstaller\loader\iu.py", line 431, in importHook
    mod = self.doimport(nm, ctx, ctx + '.' + nm)
  File "c:\pyinstall\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "F:\johan\pythonCode\jprofile\build\pyi.win32\jprofile_win32\out00-PYZ.py
z\lxml.isoschematron", line 51, in <module>
  File "lxml.etree.pyx", line 3299, in lxml.etree.parse (src\lxml\lxml.etree.c:7
2421)
  File "parser.pxi", line 1791, in lxml.etree._parseDocument (src\lxml\lxml.etre
e.c:105883)
  File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src\lxml\lx
ml.etree.c:106182)
  File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src\lxml\lxml.e
tree.c:105181)
  File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src
\lxml\lxml.etree.c:100131)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDo
c (src\lxml\lxml.etree.c:94254)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src\lxml\lxml.e
tree.c:95690)
  File "parser.pxi", line 618, in lxml.etree._raiseParseError (src\lxml\lxml.etr
ee.c:94722)
IOError: Error reading file 'C:\temp\jprofile_0.5.0_win32\jprofile.exe?175104\lx
ml\isoschematron\resources\xsl\XSD2Schtrn.xsl': failed to load external entity "
file:///C:/temp/jprofile_0.5.0_win32/jprofile.exe%3F175104/lxml/isoschematron/re
sources/xsl/XSD2Schtrn.xsl"
```

Problem here is that some Schematron-specific resources aren't included in the package.
## Workaround

Since the error suggests the missing files are expected in dir `jprofile.exe%3F175104/` I simply created a directory with that name in the source repo and then copied the underlying directory tree + resources (i.e. [jprofile.exe%253F175104](https://github.com/bitsgalore/jprofile/tree/schematronLxml/jprofile/jprofile.exe%253F175104/lxml/isoschematron/resources)>).

Ugly hack, but it works...

Side effect: `zipdir.py` now puts all underlying dirs in top-level directory. No idea why, for now I disabled zipping because I'm fed up with this shit for now  (zipping with 7zip gives expected result).

**Comment by bitsgalore** [comment]
Fixed now: <https://github.com/KBNLresearch/jprofile/commit/f2849be169619eec50d130fefc2e85b9384f682c>
